# Generated by Django 4.0.1 on 2022-01-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('longDescription', models.CharField(max_length=100)),
                ('shortDescription', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
    ]
