# Generated by Django 4.0.1 on 2022-01-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cart_product_image_subcart_cart_products_cart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AddConstraint(
            model_name='subcart',
            constraint=models.UniqueConstraint(fields=('product', 'cart'), name='once_per_product_cart'),
        ),
    ]
