# Generated by Django 4.0.1 on 2022-01-24 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_subcart_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='subcart',
            new_name='subCart',
        ),
        migrations.AlterField(
            model_name='subcart',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.product'),
        ),
    ]
